Hospital Beds Face to Face Questionnaire
HL7-DaVinci/CDS-Library pull request #15
Opened 2020-05-05 12:10 UTC by yuliumitre

This PR add face to face encounter questionnaire form for the Hospital Bed ordering. It also uses the valueset defined from vsac.

2020-05-05 19:33 UTC, yunwwang commented on HospitalBeds/R4/resources/Quesionnaire-R4-HospitalBedsFaceToFace.json
> +      "linkId": "13",
Do we need to get details for each items here? Template and CDE ask for text only.

2020-05-05 19:42 UTC, yunwwang commented on HospitalBeds/R4/resources/Quesionnaire-R4-HospitalBedsFaceToFace.json
> +          "linkId": "11.2",
May be put this one as sub item of 11.1.

2020-05-21 13:43 UTC, yuliumitre commented
@yunwwang Is there anything else? Please let me know. Thanks.

2020-05-26 13:13 UTC, lpdecelles requested changes
![image](https://user-images.githubusercontent.com/45245897/82904794-f5d75d00-9f30-11ea-840f-1d43356f873d.png)

When I click the F2F link in the CDS Hooks card I see the error above.

2020-05-26 13:34 UTC, lpdecelles commented
After I updated my value sets it seems to get further. I did have a couple questions. 
1) Should DTR fail if some of the value sets are not found?
2) It seems like some of the pre-population is not working. Am I missing something?

2020-05-26 14:43 UTC, yuliumitre commented
Hi, Larry, I merged master to this branch as it has been a while. 

The form got displayed fine for me. Please see the attached image. Regarding the pre-populated fields, do you have any specific concerns?  Please let me know. Thanks. 

![Screen Shot 2020-05-26 at 10 40 43 AM](https://user-images.githubusercontent.com/58572522/82914627-bd8a4b80-9f3d-11ea-9e8b-ffe99f758b7c.png)

2020-05-26 15:30 UTC, lpdecelles commented
OK, looks good after a forward merge from master

2020-05-26 15:30 UTC, merged