WIP: Dmeerx urological supplies order
HL7-DaVinci/CDS-Library pull request #27
Opened 2020-06-15 13:03 UTC by yuliumitre

Create this PR for easy trouble shooting.

2020-06-15 13:06 UTC, yuliumitre commented on UrologicalSupplies/R4/files/UrologicalSuppliesPrepopulation-0.1.0.cql
> +valueset "Miscellaneous Urinary Catheter Supply": 'http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1219.63'
I don't see you define those valueset in the Library-R4-Urologicoxxx.json. You need to put those valuesets as "dataRequirement".

2020-06-15 13:06 UTC, yuliumitre commented on UrologicalSupplies/R4/files/UrologicalSuppliesPrepopulation-0.1.0.cql
> +context Patient
Only need one context.

2020-06-15 13:11 UTC, yuliumitre commented on UrologicalSupplies/R4/files/UrologicalSuppliesRule-0.1.0.cql
> +    'Questionnaire/UrologicalSuppliesOrder'
To follow the naming convention, the order URI should be the full topic name: Questionnaire/UrologicalSupplies

2020-06-15 13:33 UTC, yuliumitre commented on UrologicalSupplies/R4/resources/Questionnaire-R4-UrologicalSuppliesOrder.json
> +          "extension": [
This extension should be defined in your xxx-prepopulation.cql. Then you don't need the answerOption[] section.

2020-06-15 13:35 UTC, yuliumitre commented on UrologicalSupplies/R4/resources/Questionnaire-R4-UrologicalSuppliesOrder.json
> +          "answerOption": [
Is there a valueset defined for the order? If yes, we should use it here.

2020-06-16 20:19 UTC, lpdecelles requested changes
Hello Yolanda, it looks like this PR has conflicts.

2020-06-16 20:22 UTC, yuliumitre commented
@lpdecelles I created this PR just to help Priyank for his PR with WIP (Work In Progress in the title). I am closing it now.

2020-06-16 20:22 UTC, closed without merging